"""empty message

Revision ID: 9945fa25f1d4
Revises: b4f11aaf1cac
Create Date: 2024-02-17 13:26:22.061605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9945fa25f1d4'
down_revision: Union[str, None] = 'b4f11aaf1cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
